# SPDX-FileCopyrightText: Copyright (c) 2023 - 2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


_target_: rollout.TransolverAutoregressiveRollout
_convert_: all

# --- INPUT DIMENSION CORRECTION ---
functional_dim: 22 # 1 (|E|) + 3 (coords) + 6*3 (Fourier, F=3 -> 18) = 22   
#  3 + 3 + 3*2*3 = 24 with F=3
# functional_dim = 3 + 3 + 6*num_fourier_frequencies
# --- OUTPUT DIMENSION CORRECTION ---
# Math:
#   The model predicts the next state of the physics fields.
#   1 (Epoxy VOF) + 1 (Pressure) + 3 (Velocity) = 5
#out_dim: 5
out_dim: 1            # E-field delta ΔE_t=(ΔE_x,ΔE_y,ΔE_z) 

geometry_dim: 3
slice_num: 64
n_layers: 10
use_te: false
time_input: false
include_local_features: true

### Rollout parameters ###
num_time_steps: ${training.num_time_steps}
dt: 5e-3
#use_residual: true    # vof_{t+1} = vof_t + pred (residual learning)
#debug: ${training.debug}

