# SPDX-FileCopyrightText: Copyright (c) 2023 - 2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ┌───────────────────────────────────────────┐
# │                   Data                    │
# └───────────────────────────────────────────┘  
raw_data_dir: "/workspace/aghasemi/isv/ema3d/data/ready_data/train"
raw_data_dir_validation: "/workspace/aghasemi/isv/ema3d/data/ready_data/val"
max_workers_preprocessing: 64

# ┌───────────────────────────────────────────┐
# │                 Training                  │
# └───────────────────────────────────────────┘
epochs: 2001
num_time_steps: 20            # T total (model predicts T-1 = 9 future steps)

# Performance
amp: true                     # Automatic Mixed Precision
num_dataloader_workers: 8

# Optimizer (AdamW) + Scheduler (CosineAnnealingLR)
start_lr: 5e-5
weight_decay: 1e-4
min_lr: 1e-6                  # eta_min for CosineAnnealingLR
warmup_epochs: 50              # set > 0 if you want linear warmup before cosine

# Data
num_samples: 20
num_validation_samples: 2
validation_freq: 25
save_chckpoint_freq: 50

# Paths
ckpt_path: "./checkpoints"
tensorboard_log_dir: ./tensorboard_logs

# Debug
debug: true
